### ISSUE TITLE
🐒 Corregir página de créditos

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-ninezya#103]
- [x] Quitar la palabra organiza. Solo que se vea el logo de NiñezYA

- [x] En vez de Impulsa: Comité Directivo Nacional 2023 y entra el primer ‘combo de logos’

- [x] Después: Comité Coordinador Antioquia 2023 y entra el segundo ‘como de logos’

- [x] (Dice Arturo): Sugiero eliminar la categoría de “Coordina” y poner a Imagina junto con En Flujo en la de “Desarrolla”.

- [x] (Dice Arturo): Sugiero que el nombre y logo de En Flujo siempre esté acompañado del logo o nombre de la Universidad de los Andes. Como está, parece como si el laboratorio fuera una organización independiente.

- [x] En vez de voceros consultados cada YA:  Definición indicadores por cada YA

- [x] Y pedimos agregar al final el siguiente párrafo (es un reconocimiento a quienes han estado desde el año pasado en las diferentes reuniones. Va en orden alfabético. Espero no falte nadie. Pongo al equipo de Enflujo, aunque sé que no NiñezYA de manera directa, pero puede llegar a serlo😊):

> El SIYA fue construido con la asesoría técnica de un equipo de profesionales de diferentes organizaciones que conforman NiñezYA:
>
> 
> **Fundación Éxito**
> José Villegas
> 
> **Imagina-Uniandes**
> Arturo Harker
> Daniel Mendivelso
> Juliana Gutiérrez
> 
> **Jerez&Sandoval-Medios y RS**
> Ángela Constanza Jerez
> Diana Jerez
> Ninfa Sandoval
> 
> **Laboratorio EnFlujo**
> Juan Camilo González
> Antonia Bustamante
> Julián García
> 
> **Save The Children**
> Felipe Cortés
> 
> **United Way**
> Alejandra Vargas
> 
> **World Vision**
> Sara Lara
> 
>

**Comment by 1cgonza** [comment]
arreglado en [65e463d](https://github.com/enflujo/imagina-ninezya/commit/65e463df0b4d15202276621c6dc9177496d6261b)
