### ISSUE TITLE
🔍 Hacer algo con la URL que apunta a cada YA

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-ninezya#117]
Determinar qué pasa cuando se llega a la URL de cada YA. Puede ser que envíe al primer indicador abierto. O quitarla.
En el momento se ve así:

<img width="1645" alt="image" src="https://github.com/enflujo/imagina-ninezya/assets/42554838/e44e37f8-e238-4435-a7d9-8595dd0520ad">

**Comment by 1cgonza** [comment]
resuelto en [d48b6fa](https://github.com/enflujo/imagina-ninezya/commit/d48b6fa1b79f5103f47890fefea5a021057a9e70)
