### ISSUE TITLE
:memo: Fichas y definiciones indicadores

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#119]
@dfmendivelso10 porfa avisale a @anattolia cuando este listo el Excel con información de indicadores para pasar la información depurada.

**Comment by dfmendivelso10** [comment]
Hola Juan, el estado actual de las fichas es casi del 100%, debo hacer las corrección matemática de los indicadores y me resta agregar las fichas de los 3 indicadores que añadimos recientemente. Me gustaría trabajar con Anto este miercoles para que dejemos listo eso, y para que pensemos como llamar a cada indicador.

**Comment by dfmendivelso10** [comment]
Ahí podríamos dejar claros los umbrales.

**Comment by dfmendivelso10** [comment]
Hola @anattolia te cuento los cambios que realicé:

Ya_2

2.2 y 2.3 cambie los umbrales

Ya_3

3.1; 3.2; 3.3; 3.4 cambie los umbrales

3.3 Cambie todo el indicador

**Comment by dfmendivelso10** [comment]
Hola @anattolia te comparto el link con la hoja de cálculo donde se encuentran los YA formulados, el YA7 debe tener la aclaración de que los indicadores existen, sólo que el ICBF nunca proporcionó los datos. Sin embargo, ahí te lo deje escrito.
https://uniandes-my.sharepoint.com/:x:/r/personal/df_mendivelso10_uniandes_edu_co/Documents/IMAGINA/Datos_Ni%C3%B1ez_Ya/Fichas_T%C3%A9cnicas/Ficha_T%C3%A9cnica_Indicadores_Formulados.xlsx?d=w7d01ea61210244f28407118be4355490&csf=1&web=1&e=wTXrhA

**Comment by dfmendivelso10** [comment]
@anattolia  Actualicé tambien el contexto de los siguientes indicadores **YA8**:
YA8_8.3
YA8_8.4

No vamos a tener 8.2

**Comment by 1cgonza** [comment]
@dfmendivelso10 listo, en cuanto a datos, yo ya procesé el nuevo que vi anoche 10.5 y saqué el 8.2. Con eso ya tenemos todos los datos. Ahora hace falta los textos restantes para terminar de tu lado. Estamos súper pendientes.

**Comment by dfmendivelso10** [comment]
@anattolia Anto corregi los nombres del YA 8.1 8.2 Y 8.3

**Comment by dfmendivelso10** [comment]
@anattolia Corregi el texto de todos los umbrales del YA 10. Lo deje explicito de que si bien no hay una meta pues como lo hemos venido dialogando debe ser 0.

**Comment by dfmendivelso10** [comment]
Anto @anattolia el YA 7 está completamente actualizados.
