### ISSUE TITLE
:arrow_right: La ficha técnica se sale en pantallas grandes de la página de Datos

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#130]
Sale scroll horizontal y se va moviendo hacia la derecha a medida que la pantalla es más grande.

![Screenshot from 2023-12-02 10-07-14](https://github.com/enflujo/imagina-ninezya/assets/4657617/64ab8041-c45f-46b3-b7e2-d9e2796bb6b0)

**Comment by anattolia** [comment]
@1cgonza no sé cómo probar esto sin tu pantalla pero voy a cambiarle el `max-width` y me dices si se arregla.
