### ISSUE TITLE
🐛 ¿Desnutrición aguda es porcentaje?

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#150]
Hay una confusión entre los valores y el tipo de unidad de medida en Desnutrición aguda. Según la tabla de indicadores, es un porcentaje pero los números no son coherentes con esta unidad de medida.

**Comment by dfmendivelso10** [comment]
@anattolia Ya realié la correción en la hoja de Excel, es una tasa. El indicador está calculado por cada 100,000 menores
