### ISSUE TITLE
🔢 Agregar indicadores Salud y Nutrición

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#163]
Agregar 4 indicadores a Salud y Nutrición:
1. Porcentaje de partos atendidos por personal calificado
2. Tasa de mortalidad neonatal
3. Tasa de mortalidad en menores de un año
4. Tasa de mortalidad por desnutrición en menores de 5 años

**Comment by dfmendivelso10** [comment]
Fechas de entrega, Hoja de Cálculo: Indicadores Nuevos

https://uniandes-my.sharepoint.com/:x:/r/personal/df_mendivelso10_uniandes_edu_co/Documents/Cronograma.xlsx?d=w2c3432ff5f4c4c09a192e14b5cb3a4d1&csf=1&web=1&e=KIkFsO
