### ISSUE TITLE
🔢 Agregar indicadores Educación Inicial

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#164]
Agregar 5 indicadores a Educación Inicial:

1. Niñas y niños con educación inicial en el marco de la atención integral
2. Tasa de cobertura neta de transición
3. Porcentaje de niñas y niños en primera infancia que cuentan con las atenciones
priorizadas en el marco de la atención integral
4. Porcentaje de niños y niños menores de 5 años por sitio o persona con quien
permanecen la mayor parte del tiempo entre semana
5. Miles /% niñas y niños menores de 5 años por tipo de establecimiento al que
asisten. Total nacional, departamentos y área

**Comment by dfmendivelso10** [comment]
Solo nos queda pendiente el porcentaje del tipo de oferta educativa, pública o privada. Esto solo en caso de que sea necesario.
