### ISSUE TITLE
🔢 Modificar indicadores Juego

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#165]
Modificar los indicadores de Juego:

1. Tiempo destinado al juego en familia en la semana
2. Número de programas de juego implementados en departamentos y municipios
3. Número de centros de juego/ludotecas x 1.000 niños/as
4. Número de parques o espacios seguros para el juego

**Comment by dfmendivelso10** [comment]
Anto, la próxima semana te voy a confirmar los indicadores finales de Juego y los adjunto en este issue.
