### ISSUE TITLE
✏️ Revisar que la descripción del indicador sea la correcta

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#172]
En el ejemplo el dato que se está buscando es: Proporción de nacidos vivos con bajo peso al nacer y quedó:
"indica la proporción de niños y nñas menores de 5 años que padecen de desnutrición aguda pero esa  no es" (eso no es).

-Pedir deficinión correcta a Daniel

**Comment by dfmendivelso10** [comment]
De acuerdo, la definición correcta es: "Indica la proporción de nacidos vivos a término (37 semanas o más) que nacieron con peso inferior a 2.499 gramos en un momento y territorio específicos, con respecto al total de nacidos vivos en el mismo periodo y lugar."

Revisaré cada una y te dejaré en este issue los cambios, te suena Anto ? @anattolia

**Comment by anattolia** [comment]
@dfmendivelso10 Dale! Mira también la explicación corta, por fis. Esta:
![image](https://github.com/user-attachments/assets/508bdf3c-4e7e-403f-9616-5e083e208404)

**Comment by dfmendivelso10** [comment]
Anotado
