### ISSUE TITLE
:scroll: Mejorar nombres del archivos para descarga

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#190]
Aunque suficiente el número del ya e indicador durante el desarrollo, creo que puede ser generoso con quien descarga esto desde la página si los archivos tienen en el nombre una indicación de lo que son. 

Por ejemplo: **YA_1.1_Acueducto.xlsx** es más amigable que _YA_1.1.xlsx_

**Comment by dfmendivelso10** [comment]
Entendido, podemos dejar este ajuste  para el final ?

**Comment by 1cgonza** [comment]
> Entendido, podemos dejar este ajuste para el final ?

@dfmendivelso10 Esto lo puedo hacer yo sin necesidad de cambiar los nombres de los archivos que usted me está mandando. Prefiero que me siga mandando bajo la convención que tenemos y yo me encargo de transformarlo para la descarga.

**Comment by dfmendivelso10** [comment]
Vale
