### ISSUE TITLE
🌵 EDA e IRA cambiaron mucho 

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#193]
Hay menos municipios representados y los cambios entre años son bastante distintos.

**Comment by dfmendivelso10** [comment]
Puedo extraer nuevamente los datos de los CUBOS, aunque me sorprende la menor representación de municipios. El código para procesarlos ya está optimizado, así que podemos dedicar un espacio breve, por ejemplo el lunes, para validarlo. El Ministerio ha realizado modificaciones en estos datos en comparación con la extracción utilizada para el Tablero de Salud Materno Infantil, esto puede explicar en parte esto, desafortunadamente no es algo que tengan documentado. Ya tengo la proxima semana un espacio con Arturo y en teoría con Carlos William para darle una mirada, pero la respuesta del Ministerio es clara en como se calculan y es lo que estamos haciendo.
