### ISSUE TITLE
❔ En los indicadores 3.1, 3.2 y 3.3 hay un patrón donde falta codmpio

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#207]
En estos 3 indicadores que son de las pruebas Saber 11 falta consistentemente el `codmpio` justo entre el final de un año y el inicio de otro. En las 3 tablas falta el valor de `codmpio` en las filas: **115**, **2230**, **3346**, **4462**, **5576** y **6693**.

Se ve así:

![Screenshot 2024-10-16 210957](https://github.com/user-attachments/assets/c93b9fa9-4aba-4321-bc9c-05db7f35280c)

Esto pasa entre años 2016 y 2021 pero de ahí en adelante no pasa más. 
¿cuál será el municipio que siempre falta al final del año? ¿se puede arreglar o simplemente no se sabe el municipio?

**Comment by dfmendivelso10** [comment]
Hola Juan Camilo, voy a volverlo a procesar, ya le comento.

**Comment by dfmendivelso10** [comment]
![Screenshot 2024-10-16 at 10 09 45 PM](https://github.com/user-attachments/assets/0bbf7abd-371f-4e19-b572-18ca712e8f74)

Juan Camilo lo estuve viendo para un año en particular y me doy cuenta que hay muchos missing values. No hay manera de saberlo porque en general esa misma observación tampoco tiene el código del departamento, así que voy a eliminarlos. Ese mismo municipio en realidad es el producto del calculo de todas las ovservaciones que no tienen un N/A

**Comment by dfmendivelso10** [comment]
Los volví a procesar y a subir Juan Camilo, solo resta el 3.1 por subir, aún no lo hago porque no lo puedo borrar, pero ya está listo.

**Comment by 1cgonza** [comment]
> Los volví a procesar y a subir Juan Camilo, solo resta el 3.1 por subir, aún no lo hago porque no lo puedo borrar, pero ya está listo.

Gracias! creo que no se podía borrar porque yo lo tenía abierto en ese momento. Ya lo puedes hacer.

**Comment by dfmendivelso10** [comment]
Listo Juan Camilo, ya subí el 3.1. Gracias, quedo atento.
