### ISSUE TITLE
🐛 Cuando se cambia de indicador o de nivel con depto seleccionado, se borra el borde

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#33]
Cuando se cambia el indicador con algún departamento seleccionado, se borra el borde rojo del mapa y se invierte el comportamiento de seleccionar o deseleccionar. Lo mismo pasa cuando se cambia de nivel (depto / municipio).
¡Arreglar!

**Comment by 1cgonza** [comment]
resuelto en [ba6e11b](https://github.com/enflujo/imagina-ninezya/commit/ba6e11b1f2c687d2e5756514dcc1822667771ecd)
