### ISSUE TITLE
🌡️ Definir sentido de los datos (positivo <> negativo)

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#42]
Los datos tienen un sentido que se debe definir para asignar el color. Por ejemplo, cobertura de alcantarillado es positivo (verde) si es alto, pero en mortalidad es positivo si es bajo. Este sentido lo tenemos que definir de alguna manera para pintar el mapa.

**Comment by anattolia** [comment]
@1cgonza se define desde los datos, agregamos ese campo a la estructura?
