### ISSUE TITLE
📤 Cerrar menú de años al hacer clic por fuera del menú

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#49]
Ahora toca cerrarlo haciendo clic en el botón de despliegue.

**Comment by anattolia** [comment]
@1cgonza  A mí me funciona así, yo lo había hecho. ¿No te funciona?

**Comment by 1cgonza** [comment]
@anattolia faltaba cambiar una cosita que hice en https://github.com/enflujo/imagina-ninezya/issues/49 se puede cerrar si ya te funciona.
