### ISSUE TITLE
🖌️ Colores selección mapa

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-ninezya#62]
Colores para la selección de los mapas . lista 
color que compartirán los bordes de los departamentos escogidos y las líneas en la línea de tiempo

**Comment by 1cgonza** [comment]
@Juliansintilde Esto es urgente, porfa priorizar esto

**Comment by Juliansintilde** [comment]
En eso estoy 👍🏼

**Comment by Juliansintilde** [comment]
Hay una propuesta relacionada con esto en el https://github.com/enflujo/imagina-ninezya/pull/78
Así las leyendas se reemplazan por el color del marco al elegir el departamento.
El color del borde del marco, de la letra en el nombre y del borde del municipio o departamento en el mapa, serían el mismo. Creo que con eso es claro cuál es cuál en la línea de tiempo.

![5_lineadetiempo_seleccion](https://github.com/enflujo/imagina-ninezya/assets/42554838/efbb1cef-6e78-48da-b46b-5a8410d71308)
