### ISSUE TITLE
✍🏼 Caja para texto descriptivo del indicador

### ISSUE THREAD

**Issue by Juliansintilde** [enflujo/imagina-ninezya#66]
Una caja de texto junto al nombre del indicador.

Texto:
Monospace 0
Casual 0
Grosor 433
Inclinación 0
Cursiva 0

![4_textoIndicador](https://github.com/enflujo/imagina-ninezya/assets/42554838/91a9ed17-2ec8-4a3b-a002-a4a4e88d012e)

**Comment by 1cgonza** [comment]
resuelto en [e9e6241](https://github.com/enflujo/imagina-ninezya/commit/e9e6241f238be0e480c97240b35bfb3e560988dc)
