### ISSUE TITLE
📈 Datos que faltan

### ISSUE THREAD

**Issue by 1cgonza** [enflujo/imagina-ninezya#68]
@dfmendivelso10, acá voy a ir registrando los datos que faltan. Si tienen chulo es porque ya los entregaste y funcionan, otros salen como "Listo" en la matriz inicial pero no tenemos el .xlsx en la carpeta. Paso esto acá para tener un seguimiento puntual a esto.

## Ya 1
- [ ] 1.7 - Desnutrición Aguda y Crónica **_la fuente actual está incompleta_**

## Ya 2
- ~~2.1 - Tasa de violencia en menores de 5 años **_falta excel_**~~
- ~~2.3 - Niños y niñas menores de 5 años por sitio o persona con quien permanecen la mayor parte del tiempo entre semana **_falta excel_**~~
- [ ]  2.4 - Niños y niñas menores de 5 años por tipo de establecimiento al que asisten **_falta excel_**

## Ya 3
- [x] 3.1 - Tasa de Cobertura Bruta Media _**¿Estructura matemática porcentaje?.**_
- [x]  3.2 - Resultados Pruebas Saber 11 matemáticas **_la variable se llama "lectura" pero 3.2 es la de matemáticas, ¿si son los datos?_**
- [x]  3.5 - Tasa de Repitencia **_la variable se llama "cobertura_bruta_primaria" pero esa sería la del 3.6, ¿están cruzados?_**
- [x]  3.6 - Tasa de Cobertura Bruta Primaria **_falta excel_**

## Ya 4
- [x] 4.1 - Tasa de mortalidad por Enfermedad Diarreica Aguda (EDA) en menores de 5 años _**La estructura matemática no me cuadra. Es tasa pero pareciera que la estructura que defines es porcentaje. ¿no sería así? (numerador / denominador) * 100000 (así lo teníamos en materno infantil para este indicador)**_
- [x] 4.2 -Tasa de mortalidad por Infección Respiratoria Aguda (IRA) en menores de 5 años _**Igual que el anterior, estructura matemática no coincide**_
- [x]  4.3 - Porcentaje Real de Acceso a Agua Potable **_¿Este no es idéntico al YA 1.1? ambos son la misma fuente con variable "tacued"_**

## Ya 8
- [ ]  8.1 - Proporción de jóvenes que declaran haber experimentado violencia física en los últimos 12 meses **_La matriz dice "falta procesarlos", dinos que significa el valor que actualmente está en la columna "violencia_fisica" para poder hacerlo_**
- [ ]  8.2 - Número de Procesos Administrativos de Reestablecimientos de Derechos por el Consumo de Sustancias Psicoactivas  **_La variable se llama "violencia_fisica" y no "consumo_sustancias" como aparece en la matriz ¿si son estos los datos?_**

## Ya 9

_**Faltan todos.**_

## Ya 10
- [ ]  10.2 - Ataque a escuelas por grupos al margen de la ley **_falta excel_**
- [ ]  10.4 - Bajo Logro Educativo (Porcentaje de niños que se encuentran cursando en extra edad) **_falta excel_**
- [ ]  10.5 - Maltrato Físico (# de ataques a menores de edad por parte de un cuidador, familiar o padre) **_falta excel_**

**Comment by dfmendivelso10** [comment]
Hola @1cgonza, subo 3 nuevos indicadores: 

- 2.4 Porcentaje de Alumnos que asisten a un colegio Público
- 2.6 Porcentaje de Alumnos que cursan preescolar y asisten a un colegio Público
- 2.7 Porcentaje de Alumnos que cursan primaria y asisten a un colegio Público

**Comment by dfmendivelso10** [comment]
Hola @1cgonza te comento que el indicador 2.5 fue renombrado como 2.6 y el 2.6 como 2.5. Quieres que renombre los datos en OneDrive ?

**Comment by dfmendivelso10** [comment]
@1cgonza  Hola Juan Camilo, el YA 2 Educación Inicial tendrá la siguiente estructura:

- YA 2_2.1 Cobertura transición. Los Datos ya están listos * Los valores superiores a 100% son normales.
- YA 2_2.2 Reprobación transición (reprobacion_transicion) 
- YA 2_2.3 Repitencia transición (repitencia_transicion) 
- YA 2_2.4 Deserción transicion intra-anual (desercion_transicion)
- YA 2_2.5 Proporción de estudiantes en el sector oficial (oficial_privado) ** Este es el indicador que hay que pensar como representarlo porque tiene dos columnas, una columna corresponde a los que asisten a colegios públicos y la otra a colegios privados.

Los demás indicadores fueron borrados. Ya se encuentran actualizados en One Drive estas modificaciones.

**Comment by dfmendivelso10** [comment]
@1cgonza Hola juan Camilo, el YA 3 Educación preescolar, básica y media ahora tiene la siguiente estructura:

- YA3_3.1 (oficial_privado) Proporción de estudiantes en el sector oficial.
- YA3_3.2 (matematicas) Puntaje Saber 11 Matemáticas
- YA3_3.3 (lectura) Puntaje Saber 11 - Lectura
- YA3_3.4 (total) Puntaje Saber 11 
- YA3_3.4 (cobertura_primaria)  Cobertura bruta primaria
- YA3_3.5 (cobertura_secundaria)  Cobertura bruta secundaria
- YA3_3.6 (cobertura_media)  Cobertura bruta media
- YA3_3.7 (reprobacion_primaria) Reprobación primaria
- YA3_3.8 (reprobacion_secundaria) Reprobación secundaria
- YA3_3.9 (reprobacion_media) Reprobación media
- YA3_3.10 (repitencia_primaria) Repitencia primaria
- YA3_3.11 (repitencia_secundaria) Repitencia secundaria
- YA3_3.12 (repitencia_media) Repitencia media
- YA3_3.13 (desercion_primaria) Deserción primaria intra-anual
- YA3_3.14 (desercion_secundaria) Deserción secundaria intra-anual
- YA3_3.15 (desercion_media) Deserción media intra-anual

**Comment by dfmendivelso10** [comment]
@1cgonza Hola Juan Camilo, ya están listos 8.1 Violencia y 8.4 Homicidios. 8.2 que es consumo de substancia. Falta procesar el codmpio del 8.3 y ya tendríamos los Ya
