### ISSUE TITLE
🎨 Agregar leyendas de color de línea a Línea de tiempo

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#71]
Agregar leyendas y cambiar colores de líneas a Línea de tiempo para saber cuál es cuál.

**Comment by 1cgonza** [comment]
@Juliansintilde Esto cómo va? alguna propuesta? es urgente definir el sistema de leyendas de la línea de tiempo.

**Comment by Juliansintilde** [comment]
Hay una propuesta relacionada con esto en el #79.
Así las leyendas se reemplazan por el color del marco al elegir el departamento. 
El color del borde del marco, de la letra en el nombre y del borde del municipio o departamento en el mapa, serían el mismo. Creo que con eso es claro cuál es cuál en la línea de tiempo.

![5_lineadetiempo_seleccion](https://github.com/enflujo/imagina-ninezya/assets/42554838/efbb1cef-6e78-48da-b46b-5a8410d71308)
