### ISSUE TITLE
👓 Agregar información sobre cómo usar el tablero

### ISSUE THREAD

**Issue by anattolia** [enflujo/imagina-ninezya#96]
Agregar información sobre cómo usar el tablero. ¿Lo ponemos en el inicio también o aparte?

**Comment by Juliansintilde** [comment]
Yo diría que mejor aparte 🤔 
De pronto otra página a modo de instructivo. 

Para no ponerlos a programar, ¿qué tal algo así: pero con capturas de pantalla?

https://www.opportunityatlas.org/
![image](https://github.com/enflujo/imagina-ninezya/assets/42554838/627055ed-4998-421e-905d-c05cc5a76fdc)
